### ISSUE TITLE
Scale back nightly version to get it closer to stable and eventually to stable

### ISSUE THREAD

**Issue by JRAndreassen** [sreeise/graph-rs#290]
@sreeise ...

Is there a way to get rid of the requirement to use nightly unstable features...

The requirement is causing all kinds of other unstable features to be included.

One of which causes a runaway process in the futures library...

So, is there a way to at least make it optional ?

 Thanks
  JR

**Comment by sreeise** [comment]
yeah so Ive been working toward getting all of the graph API's into the project and once this is done I plan on trying to scale back the nightly build and releasing it on [crates.io](https://crates.io/). Currently, I just update the nightly every few months for development which is why its on a newer version. So, its coming not long from now. I will try to see what I can do in the meantime. I may possibly be able to get it to an earlier nightly version. `async_closure` and `type_alias_impl_trait` are the two main nightly features that are used.

**Comment by JRAndreassen** [comment]
P.S. I've changed mu local toolchain to just "Nightly"...
It seems to be working.
It seems also, that the runaway process may have been related to combining
tokio and futures::executor::block_on...
Helluva thing...

**Comment by sreeise** [comment]
Futures is a one way street to problems sometimes. Ill leave this open so I can make sure to look at the nightly version in the future.

**Comment by sreeise** [comment]
Master branch is now on stable. Closing. I will put the new version on crates.io soon.
