### ISSUE TITLE
How to set the tenant ID

### ISSUE THREAD

**Issue by Timmmm** [sreeise/graph-rs#305]
When using the `auth_code_grant.rs` example I get this OAuth error:

```
AADSTS50194: Application (my app) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
```

I had the same error when I was trying to use the Python `o365` library, and fixed it by just setting the tenant ID like this:

```python
credentials = (client_id, client_secret)

account = Account(credentials, tenant_id='....')
```

How do I do the same thing with `graph-rs-sdk`?

**Comment by sreeise** [comment]
@Timmmm Hey Tim, sorry I am just now seeing this. Let me see if I can find an example that shows how to do this.

**Comment by sreeise** [comment]
@Timmmm Because we don't use the tenant id in any other place besides the URL's for requesting access tokens and refresh tokens, you would actually need to format this in the url itself:
 ```rust
    let tenant_id = "TENANT_ID";
    let access_token_url = format!("https://login.microsoftonline.com/{}/oauth2/v2.0/token", tenant_id);

    let mut oauth = OAuth::new();
    oauth
        .client_id("CLIENT_ID")
        .client_secret("CLIENT_ID")
        .access_token_url(&access_token_url);
 ```
 
 You will want to do this for the authorization url as well as the access and refresh token url's. For instance:
 Replace the word `common` in each url below:

```rust
    oauth
        .authorize_url("https://login.microsoftonline.com/common/oauth2/v2.0/authorize")
        .access_token_url("https://login.microsoftonline.com/common/oauth2/v2.0/token")
        .refresh_token_url("https://login.microsoftonline.com/common/oauth2/v2.0/token");
        
  // Replace the above with:
     oauth
        .authorize_url("https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize")
        .access_token_url("https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token")
        .refresh_token_url("https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token")

```

Now that you bring this issue up though, I think adding a way to just set the tenant id would be a great addition. I will create a ticket for it so that it can be done in future work. 

Let me know if this helps. Thanks.

**Comment by Timmmm** [comment]
Ah that's a lot easier than I was expecting, thanks!
