### ISSUE TITLE
List deleted items not working

### ISSUE THREAD

**Issue by DevLazio** [sreeise/graph-rs#325]
It is currently not possible to supply the required OData cast type for the directory/deletedItems 

https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http#http-request

How do you want to implement this ? As 4 differents endpoints ? With a new method to specify the Odata cast type ? Allow the user to modify the inner url directly ?

**Comment by sreeise** [comment]
Hmm, good question. This might be worth looking at adding some custom requests with its own request api directory that is not part of code generation for these. This would be similar to how [extended_properties](https://github.com/sreeise/graph-rs/blob/master/src/extended_properties/request.rs) is currently done. It could be called `deleted_items` and I believe there are some other parts of the graph API that cover deleted items in other ways as well so that is something to look into.

**Comment by sreeise** [comment]
If those specific odata cast types are used in other API requests then its probably better to add them as methods where the current OData types can be set: https://github.com/sreeise/graph-rs/blob/20ed58450ab1161793365df3271cfc4802fde5b1/graph-http/src/intoresponse.rs#L51-L113

**Comment by DevLazio** [comment]
There is at least the https://graph.microsoft.com/v1.0/directoryObjects endpoint that is not usable without the same cast types ("microsoft.graph.user", etc).
And it seems that the OData cast type is usable for a lot of other requests : https://docs.microsoft.com/en-us/search/?terms=OData%20cast%20type&scope=graph&products=%2Fdevrel%2F5fc61396-d075-4560-aece-fdbda73d243f
