### ISSUE TITLE
Graph concurrency deadlock

### ISSUE THREAD

**Issue by DevLazio** [sreeise/graph-rs#349]
It looks like I found another way to deadlock the application when preparing bunch of requests at the same time.

This time, I was able to reproduce the deadlock without send the requests : 
`    let _a = client
        .v1();`
is enough to trigger it as shown [here](https://github.com/DevLazio/graph-rs-concurrency-issue/blob/b385a3feee3ed7fef8c216da5bc66bda0673959c/src/main.rs#L107).

[Requesting with reqwest does not trigger the deadlock. ](https://github.com/DevLazio/graph-rs-concurrency-issue/blob/b385a3feee3ed7fef8c216da5bc66bda0673959c/src/main.rs#L57)
On my computer, this program deadlock after 128 "Fetching license detail for /.." but when I uncomment the next line [".users()"](https://github.com/DevLazio/graph-rs-concurrency-issue/blob/b385a3feee3ed7fef8c216da5bc66bda0673959c/src/main.rs#L109)  the deadlock appears twice as fast than without this line, after 64 calls.
Uncommenting the next line divide again the number of calls required by two, etc.
In the end, only 16 calls are required to trigger the deadlock with this code :
```
 let _license_details: GraphResponse<LicenseDetails> = client
          .v1()
          .users()
          .id(user_id)
          .list_license_details()
          .json().await?;
```

I tried :
- adding a tracing debug
- using tokio-console to look for locked mutexes (not the case)
- upgrading every dependency of every crate of graph_rs (except handlebars)

and I still have no clue.

**Comment by DevLazio** [comment]
When looking around for a solution I found this : https://users.rust-lang.org/t/tokio-executor-block-on-freezing-and-handle-block-on-causing-cannot-start-a-runtime-from-within-a-runtime/63576
and https://users.rust-lang.org/t/simplest-possible-block-on/48364/26

Basicaly, doing async -> sync -> async is messy. 

Possible solutions : 
- find a proper way to do that
- make the async client fully async, removing the RequestClient trait ?
- make the sync implementation relies on the async one (Reqwest style)

**Comment by DevLazio** [comment]
I tried using [spin_on](https://docs.rs/spin_on/latest/spin_on/) as a replacement for `futures::executor::block_on()` and it does not work better.

So I went down into the rabbit hole of trying to make the whole `.v1().users().id(user_id).list_license_details()` function chain async. It's relatively easy for `v1()`, next to impossible for the rest without duplicating half the codebase, including macros and requests.rs files.

**Comment by DevLazio** [comment]
> Heyyy, nice work. I havnt had a good chance to go through all this yet, but from what I gather it seems like this is happening in part because of using the library in a way that its not meant to be? Meaning
> 
> ```
> client.v1();
> ```
> 
> On that example I was pretty much already aware that could cause a dead lock, I just didn't think anyone would intentionally do that. But I get your point haha.
> 

Actually the library deadlock when used the way it should be. I was just demonstrating that It was possible to deadlock with a single function. 

> And the other part of this is, which you really thought of and made me realize now is that it doesn't make sense to use futures::executor_block_on, which just causes it to run on a single thread, in what is meant to be asynchronous code. When I wrote this originally it was like you said, not using it would require duplicating a ton of code. But based on what I am seeing here, the asynchronous apis will continue to run into problems. This is some really good research on your part. Thank you for taking this up.

I might add that while researching a way to fix that I found a few ressources such as [this story](https://rust-lang.github.io/wg-async/vision/submitted_stories/status_quo/barbara_bridges_sync_and_async.html). At the end you can read : 

> Regardless, the synchronous reqwest API is actually itself implemented using block_on: so Barbara would have ultimately hit the same issues. Further, not all crates offer synchronous APIs -- some offer only async APIs. In fact, these same issues are probably the sources of those panics that Barbara encountered in the past.

If we are going to use an async stack at some point it might be better to remove a "layer" of the sync / sync / async pile.


> Wrapping the generic Client in an `Arc` is a little odd, especially considering the `HttpClient` which is what that generic Client represents is already wrapped in an `Arc<Mutex>`. 

Agreed. That's the only way I found to spawn a tokio task without running into a 'static lifetime issue and breaking the least possible the API.

> Off the top of my head I was thinking maybe of possibly doing a custom Future trait implementation where we control whats happening. The downside to that would be that its pretty low level code to deal with.

That's way above my level, but I'll be happy to help.

**Comment by sreeise** [comment]
> If we are going to use an async stack at some point it might be better to remove a "layer" of the sync / sync / async pile.

The more I look at this, the more I think we will have to rework the network code and remove or change layers like you said.

> make the async client fully async, removing the RequestClient trait ?

I think you already mentioned you found this out while testing/researching, but the trait is in part what helps to prevent us from doing massive code duplication. I'm not sure what other solutions there are if we do remove that at the moment. But i'm down to look for them, or listen to any suggestions.

> make the sync implementation relies on the async one (Reqwest style)

After doing more research tonight this is the approach that I think may work the best. I am still researching but it may be the best solution in terms of not having to rewrite an overwhelming amount of code and at the same time I think we could possibly do the fix by only making internal changes to the graph-http portion/crate. I am not 100% that this is the case but I think that any changes outside of that crate would probably be minimal. 

But I also don't want to just do the minimal required solution for the sake of time or less complexity either. I am more than OK with doing a much larger change if the solution is good enough to warrant it and its something we can build on.

**Comment by sreeise** [comment]
Looking into the possibility of changing the synchronous client to use the asynchronous client internally and it looks like this will probably mean that the macros will need to be changed to account for async/await. Currently those just don't have any async functions except for downloads. I havnt fleshed out what would need to be done yet, but it will probably get tricky if it means having two separate macros for a single request, one for async and one for sync. Meaning the underlying macro could potentially just create two methods, one for sync and one for async, but that may require some workaround such as how its done for downloads using two separate impl blocks. 
https://github.com/sreeise/graph-rs/blob/7aeeeae2e92ef622dc6e657acefb145c90e56222/src/service_announcement/request.rs#L106-L126

Something to check into is if there may be a better way to abstract this so that we don't have to do two separate impl like in the above example. Its been also been a while since the `graph-http` crate was first implemented, including the `RequestClient` trait, so there may be better/newer ways to abstract this given that Rust is a newer and constantly evolving language.

**Comment by sreeise** [comment]
@DevLazio Its possible we may just be able to use `std::sync::Mutex` instead of `tokio::sync::Mutex`. Based on what ive read from tokio docs, as long as we don't use the `MutexGuard` across an `.await` which is easier said then done. I opened a branch that changes the async client to use `std::sync::Mutex` but have not done extensive testing or attempted to clean up where/how locking the mutex is done with the `.await` consideration in mind. I am going off of the information [here](https://tokio.rs/tokio/tutorial/shared-state#holding-a-mutexguard-across-an-await)

One thing that may work is making sure that first build the Request using RequestBuilder and then passing that along to the caller in some type of other object that can convert the response such as IntoResponse does but without having a reference to the client as a field. This will make sure that we never use it across an await as its always out of the scope of the internal client before the await ever gets called.

**Comment by DevLazio** [comment]
I just tried your fix and indeed it appears to have succesfully resolved the deadlock, well done !

I'll try this branch in a more complexe program and try to find a forgotten lock across .await point.
This reminds me that [this article](https://fasterthanli.me/articles/a-rust-match-made-in-hell) was exactly about this problem.

**Comment by DevLazio** [comment]
I could not find a single problem with you fix. Very well done !
