### ISSUE TITLE
Create Team results in Reqwest Error

### ISSUE THREAD

**Issue by JoschuaL** [sreeise/graph-rs#364]
So when creating a Team with

```rust
graph.v1().teams().create_team(...)
```

the intended response from graph will have content length zero.

However, currently, even on a successfull request, the response returned by graph-rs is 

```rust
Err(ReqwestError(reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }))
```

This is most likely because the response is in fact empty, and this is not an error.

This is in so far problematioc that the graph response still has some headers that are needed to get the id of the newly created team.

but since a request error is returned, the headers can not be retrived.

Test code:

```rust
let graph = ...;
let json = serde_json::json!({
  "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
  "displayName": "My Sample Team",
  "description": "My Sample Team’s Description"
});
let resp = graph.v1().teams().create_team(&graph_team).send().await;
std::println!("{resp:?}");
```

**Comment by sreeise** [comment]
This is due to the macro setting the expected response as serde_json::Value either by default for a POST or because the OpenApi has the response set to return some type of object or JSON value and doesnt otherwise make it clear on the content. Thanks for reporting. Should be an easy fix.

**Comment by sreeise** [comment]
I am thinking about updating Teams because it hasnt been updated in a while. But if you want too you can update this line https://github.com/sreeise/graph-rs/blob/3740b4db4bbd0af23f74fadf74b2dd79c13de6c6/src/teams/request.rs#L79

and replace `serde_json::Value` with `NoContent` and the request should work after that.

**Comment by sreeise** [comment]
Fixed in #365 

Thanks @JoschuaL for the contribution. I commented this in the PR also but let me know if you need this in the crate or if its ok just in master for right now. I don't usually update the crate until there are more changes in master but I can do so if you need it.

**Comment by drernie** [comment]
I am not sure if this is related, but for every call I currently seem to be getting the same error message:
```
response: Err(ReqwestError(reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }))
```
I probably have some other configuration error causing methods to return an empty body...

**Comment by sreeise** [comment]
> I am not sure if this is related, but for every call I currently seem to be getting the same error message:
> 
> ```
> response: Err(ReqwestError(reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }))
> ```

Hey @drernie 

The issue in this ticket was happening because of a previous version of the library would convert the Reqwest response to a response that was part of this crate. And in doing so would attempt to convert the request body also with the thinking that there actually would be a response body for any POST request. But we changed to just returning the Reqwest response in every case except for paging calls. So, we no longer parse the request body and leave this up to the user.

If your calling the create teams endpoint and attempting to parse the response body then yes you will probably get that error because that specific endpoint does not return a reponse body. 

> 
> I probably have some other configuration error causing methods to return an empty body...

Are you saying that every call you make, on different APIs, is returning an empty response body?

**Comment by drernie** [comment]
> every call you make, on different APIs, is returning an empty response body?

Yes. It feels like some other error is getting caught, and returning an empty response body, which is triggering this error.

I finally figured out how to properly set up Azure Graph authentication using the Python SDK, so I will try this again in Rust...

**Comment by sreeise** [comment]
> > every call you make, on different APIs, is returning an empty response body?
> 
> Yes. It feels like some other error is getting caught, and returning an empty response body, which is triggering this error.
> 
> I finally figured out how to properly set up Azure Graph authentication using the Python SDK, so I will try this again in Rust...

Uh, yeah that is odd. I will check to see if there is issues by calling the create teams endpoint. But if your having issues with every API it could very well be an authentication/authorization issue. Possibly calling an API using an app registration that doesn't have the permissions to call that API (which would be added in Azure). Or something similar. Have you checked that your permissions are correct? Just for reference, this is what I am referring to: https://learn.microsoft.com/en-us/graph/auth/auth-concepts#microsoft-graph-permissions and https://learn.microsoft.com/en-us/entra/identity-platform/permissions-consent-overview#consent

What type of auth flow are you running? Meaning is it client credentials, auth code grant, device code, etc.
