### ISSUE TITLE
Upload files using bytes::Bytes

### ISSUE THREAD

**Issue by fdoyon** [sreeise/graph-rs#399]
At the moment it seems that a file has to be saved to the local filesystem in order to be uploaded to the Graph API.

I do a lot of transfer between S3 and Office and as such the data I need to upload is often available in memory, would it be possible to use a `byte::Byte` from the `byte` crate to specify the contents of an upload? Or even a `Read` / `AsyncRead`?

**Comment by sreeise** [comment]
Yeah its certainly possible, just not available yet, and a good idea that should be added to the library.

**Comment by sreeise** [comment]
@fdoyon Are you wanting to do this for both normal uploads as well as upload sessions? I am currently looking to see what the best way to do this would be and right now files are just read into a string for uploads but upload sessions require bytes to work regardless so its not too much different to do that for uploads, either by taking in bytes or by converting a file to bytes.

**Comment by sreeise** [comment]
@fdoyon The next release that will be merged, moving to async by default, will provide the ability to pass a Read or AsyncReadExt to do uploads and upload sessions. Feel free to try it out on this branch [async_default](https://github.com/sreeise/graph-rs/tree/async_default)

There is a lot of breaking changes so you won't be able to just switch to the new branch in your dependencies. But changes from the user perspective are minimal. I have updated all examples and the README so that its easy to see what you need to do. There is an [upload_session](https://github.com/sreeise/graph-rs/blob/async_default/examples/upload_session.rs) example as well as several [upload](https://github.com/sreeise/graph-rs/blob/async_default/examples/drive/upload_file.rs) examples.

If you do check it out let me know what you think and if it works for you.
