### ISSUE TITLE
Adding a report only available in beta

### ISSUE THREAD

**Issue by DevLazio** [sreeise/graph-rs#408]
I'm interrested into adding the [credentialUserRegistrationDetails report](https://learn.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0), unfortunately it is only available in the beta API for now. 

Adding 
```rust
    get!(
        doc: "List credentialUserRegistrationDetails",
        name: list_credential_user_registration_details,
        path: "/reports/credentialUserRegistrationDetails"
    );
```
in https://github.com/sreeise/graph-rs/blob/master/src/reports/request.rs works fine (if you use the beta client). 
Do you mind If I do a pull request to add it ?

**Comment by sreeise** [comment]
eah sure I don't mind. I made sure the specific request your talking about wasn't in the OpenAPI that these are generated from as well just to see if I missed something when generating them. But `credentialUserRegistrationDetails` is not in the OpenAPI paths at all. If you ever want to know how to check if something can be generated or if it has to be done manually you can do:

```rust
use graph_codegen::openapi::OpenApi;

fn main() {
    // Finds any path that has this in it not just Reports paths.
    find_path("credentialUserRegistrationDetails");
}

pub fn find_path(path: &str) {
    let mut open_api = OpenApi::default();
    let paths = open_api.filter_path_contains(path);
    for (path, _) in paths.iter() {
        println!("{path:#?}");
    }

    if paths.is_empty() {
        println!("Found no path matching: {path:#?}");
    }
}

```

I havn't added a way to make sure the codegen, under 1.0.0, understands manual requests to the point that it generates those with it. So the best way to do it would be to create a manual_request.rs under the reports directory and just do:

src/reports/mod.rs
```rust
mod manual_request;
mod request;

pub use manual_request::*;
pub use request::*;
```

src/reports/manual_request.rs
```rust
use crate::api_default_imports::*;
use crate::reports::ReportsApiClient;

impl ReportsApiClient {
    get!(
        doc: "List credentialUserRegistrationDetails",
        name: list_credential_user_registration_details,
        path: "/reports/credentialUserRegistrationDetails"
    );
}

```

This way if reports ever gets regenerated the manual requests don't get overwritten. The mod.rs will get overwritten but you will know that happened because the build will tell you it. And its not hard just fix mod.rs.
